### ISSUE TITLE
SSL/Multithreading patches not complete in repository

### ISSUE THREAD

**Issue by jens-maus** [nega0/xmlrpcpp#1]
I am currently looking into getting xmlrpcpp to support HTTPS/SSL connections. Thus, I stumbled over your interesting xmlrpcpp patchset. However, looking at the `09_xmlrpc++_xxxx` patch file (https://github.com/nega0/xmlrpcpp/blob/master/patches/09_xmlrpc%2B%2B_Support%20for%20SSL%2C%20Multithreading%2C%20and%20building%20as%20RPM.diff.nega) reveals that this patch seems to be incomplete.

E.g., in there a file named `XmlRpcConnectionSsl.cpp` is referenced, but is not part of the patch itself (see https://github.com/nega0/xmlrpcpp/blob/master/patches/09_xmlrpc%2B%2B_Support%20for%20SSL%2C%20Multithreading%2C%20and%20building%20as%20RPM.diff.nega#L646-L647). It actually seems you have executed the diff without the "-N" option.

Do you still have after all these years your xmlrpcpp patches around and could update the patch files in your repository with the missing pieces. Or can you simply send me your whole xmlrpcpp repository folder including `XmlRpcConnectionSsl.cpp` and friends so that I can generate a fork of your repository and continue the work you probably haven't touched for many years?!? Thanks.

**Comment by jens-maus** [comment]
Please note that after some investigation I found the corresponding patch file including the missing files from here:

https://sourceforge.net/p/xmlrpcpp/patches/24/

**Comment by nega0** [comment]
Thanks. I'll look for the pre-github repo and make sure I haven't touched this missing file, and I'll add it here so you can do a clean fork if you need.

**Comment by nega0** [comment]
I found the pre-github repo, but not the pre-git repo :wink:

The patch is now correct. 

Note that like patch 07, patch 09 hasn't been applied to [master](/nega0/xmlrpcpp/tree/master). 09 applies to [xmlrpc++0.7](https://sourceforge.net/projects/xmlrpcpp/files/xmlrpc++/Version%200.7/). To use it with my fork, you'll need to do something like:

```Shell
git clone ...
cp "patches/09_xmlrpc++_Support for SSL, Multithreading, and building as RPM.diff.nega" /tmp/foo
git reset --hard ced32ea
patch -p1 < /tmp/foo
```

I imagine that at the time, I had a good reason for not including 07 and 09 in [master](/nega0/xmlrpcpp/tree/master). I probably wasn't using them and included them for completeness.
